<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HealthTracker.Worker-683cb4eb-53d6-4956-99b7-e951b6467514</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="13.2.1" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HealthTracker.ServiceDefaults\HealthTracker.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
